# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui.txt'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 564)
        Dialog.setAutoFillBackground(False)
        self.u_name_label = QtWidgets.QLabel(Dialog)
        self.u_name_label.setGeometry(QtCore.QRect(100, 260, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.u_name_label.setFont(font)
        self.u_name_label.setObjectName("u_name_label")
        self.pass_label = QtWidgets.QLabel(Dialog)
        self.pass_label.setGeometry(QtCore.QRect(100, 320, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pass_label.setFont(font)
        self.pass_label.setObjectName("pass_label")
        self.login_btn = QtWidgets.QPushButton(Dialog)
        self.login_btn.setGeometry(QtCore.QRect(272, 417, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_btn.setFont(font)
        self.login_btn.setObjectName("login_btn")
        self.signu_btn = QtWidgets.QPushButton(Dialog)
        self.signu_btn.setGeometry(QtCore.QRect(410, 417, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.signu_btn.setFont(font)
        self.signu_btn.setObjectName("signu_btn")
        self.username_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.username_lineEdit.setGeometry(QtCore.QRect(250, 250, 281, 41))
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.password_lineEdit.setGeometry(QtCore.QRect(250, 330, 281, 41))
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 30, 431, 151))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.u_name_label.setText(_translate("Dialog", "Username"))
        self.pass_label.setText(_translate("Dialog", "Password"))
        self.login_btn.setText(_translate("Dialog", "Login"))
        self.signu_btn.setText(_translate("Dialog", "Signup"))
        self.label.setText(_translate("Dialog", "Login form"))
