# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signup.ui.txt'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(740, 562)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 30, 471, 191))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pass_label = QtWidgets.QLabel(Dialog)
        self.pass_label.setGeometry(QtCore.QRect(130, 290, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pass_label.setFont(font)
        self.pass_label.setObjectName("pass_label")
        self.u_name_label = QtWidgets.QLabel(Dialog)
        self.u_name_label.setGeometry(QtCore.QRect(130, 230, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.u_name_label.setFont(font)
        self.u_name_label.setObjectName("u_name_label")
        self.signup_button = QtWidgets.QPushButton(Dialog)
        self.signup_button.setGeometry(QtCore.QRect(350, 450, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.signup_button.setFont(font)
        self.signup_button.setObjectName("signup_button")
        self.uname_line = QtWidgets.QLineEdit(Dialog)
        self.uname_line.setGeometry(QtCore.QRect(280, 220, 281, 41))
        self.uname_line.setObjectName("uname_line")
        self.email_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.email_lineEdit.setGeometry(QtCore.QRect(280, 300, 281, 41))
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.pass_label_2 = QtWidgets.QLabel(Dialog)
        self.pass_label_2.setGeometry(QtCore.QRect(130, 360, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pass_label_2.setFont(font)
        self.pass_label_2.setObjectName("pass_label_2")
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.password_lineEdit.setGeometry(QtCore.QRect(280, 370, 281, 41))
        self.password_lineEdit.setObjectName("password_lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Create account"))
        self.pass_label.setText(_translate("Dialog", "Email"))
        self.u_name_label.setText(_translate("Dialog", "Username"))
        self.signup_button.setText(_translate("Dialog", "Signup"))
        self.pass_label_2.setText(_translate("Dialog", "Password"))
